"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/app/api/_server/db/prisma";
import { requireAdmin } from "@/app/api/_server/auth/session";
import { uploadImages } from "@/app/api/_server/services/imagekit.service";

const vesselSchema = z.object({ name: z.string().trim().min(2).max(120), imoNumber: z.string().trim().min(5).max(30) });
const equipmentSchema = z.object({ vesselId: z.string().uuid(), name: z.string().trim().min(2).max(120), category: z.enum(["PROPULSION", "AUXILIARY", "NAVIGATION", "SAFETY", "ELECTRICAL", "DECK", "OTHER"]), lifespanMonths: z.coerce.number().int().positive().max(1000), lastServiceDate: z.coerce.date() });
function getPhotos(formData: FormData) { return formData.getAll("photos").filter((item): item is File => item instanceof File && item.size > 0); }
function getPhotoUrls(formData: FormData) { return formData.getAll("photoUrls").filter((item): item is string => typeof item === "string" && item.length > 0); }
function validateImageUrls(urls: string[]) { const endpoint = process.env.IMAGEKIT_URL_ENDPOINT?.trim().replace(/\/$/, ""); if (!endpoint) return false; return urls.every(url => url.startsWith(endpoint)); }

export async function createVessel(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const parsed = vesselSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Nama kapal dan nomor IMO wajib diisi." }; try { await prisma.vessel.create({ data: parsed.data }); revalidatePath("/boss"); revalidatePath("/boss/vessels"); return { success: true }; } catch { return { error: "Nomor IMO sudah digunakan atau data tidak valid." }; } }
export async function updateVessel(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const id = String(formData.get("id")); const parsed = vesselSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success || !id) return { error: "Data kapal tidak valid." }; try { await prisma.vessel.update({ where: { id }, data: parsed.data }); revalidatePath("/boss"); revalidatePath("/boss/vessels"); return { success: true }; } catch { return { error: "Kapal gagal diperbarui." }; } }
export async function deleteVessel(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const id = String(formData.get("id")); try { await prisma.vessel.delete({ where: { id } }); revalidatePath("/boss"); revalidatePath("/boss/vessels"); return { success: true }; } catch { return { error: "Kapal gagal dihapus." }; } }
export async function createEquipment(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const parsed = equipmentSchema.safeParse(Object.fromEntries(formData)); const photos = getPhotos(formData); const photoUrls = getPhotoUrls(formData); if (!parsed.success || (photoUrls.length < 1 && photos.length < 1) || photoUrls.length > 10 || photos.length > 10) return { error: "Lengkapi data equipment dan unggah 1-10 foto." }; try { const urls = photoUrls.length ? photoUrls : await uploadImages(photos, "/equipment"); if (!validateImageUrls(urls)) return { error: "URL photos ImageKit tidak valid." }; const equipment = await prisma.equipment.create({ data: { ...parsed.data, status: "OPERATIONAL", photos: { create: urls.map(url => ({ url })) } } }); revalidatePath("/boss"); revalidatePath("/boss/equipment"); return { success: true, id: equipment.id }; } catch { return { error: "Equipment gagal dibuat. Periksa ImageKit dan data yang dikirim." }; } }
export async function updateEquipment(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const id = String(formData.get("id")); const parsed = equipmentSchema.safeParse(Object.fromEntries(formData)); const photos = getPhotos(formData); const newPhotoUrls = getPhotoUrls(formData); const requestedExisting = formData.getAll("existingPhotoUrls").filter((value): value is string => typeof value === "string" && value.length > 0); const replaceExisting = formData.get("replaceExistingPhotos") === "true"; if (!id || !parsed.success || photos.length > 10 || newPhotoUrls.length > 10 || requestedExisting.length > 10 || newPhotoUrls.length + photos.length + requestedExisting.length > 10) return { error: "Foto equipment maksimal 10." }; try { const currentPhotos = await prisma.equipmentPhoto.findMany({ where: { equipmentId: id }, select: { url: true } }); const currentUrls = new Set(currentPhotos.map(photo => photo.url)); const keptExisting = replaceExisting ? requestedExisting.filter(url => currentUrls.has(url)) : currentPhotos.map(photo => photo.url); const uploadedUrls = newPhotoUrls.length ? newPhotoUrls : (photos.length ? await uploadImages(photos, "/equipment") : []); if (!validateImageUrls(uploadedUrls)) return { error: "URL photos ImageKit tidak valid." }; const finalUrls = [...keptExisting, ...uploadedUrls]; if (finalUrls.length < 1 || finalUrls.length > 10) return { error: "Equipment wajib memiliki 1-10 foto." }; await prisma.equipmentPhoto.deleteMany({ where: { equipmentId: id } }); await prisma.equipment.update({ where: { id }, data: { ...parsed.data, photos: { create: finalUrls.map(url => ({ url })) } } }); revalidatePath("/boss"); revalidatePath("/boss/equipment"); return { success: true }; } catch { return { error: "Equipment gagal diperbarui." }; } }
export async function deleteEquipment(formData: FormData) { await requireAdmin(); if (!prisma) return { error: "Database tidak tersedia." }; const id = String(formData.get("id")); try { await prisma.equipment.delete({ where: { id } }); revalidatePath("/boss"); revalidatePath("/boss/equipment"); return { success: true }; } catch { return { error: "Equipment gagal dihapus." }; } }
